/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class issueBook extends javax.swing.JFrame {

    /**
     * Creates new form issueBook
     */
    public issueBook() {
        initComponents();
    }

  public void getBookDetails(){
        
         int bookId = Integer.parseInt(txt_bookId.getText());
         
try{

Class.forName("com.mysql.jdbc.Driver");

Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","");

 PreparedStatement pst = con.prepareStatement("select * from bookdetails where book_id = ?");
 pst.setInt(1,bookId);
ResultSet rs =(ResultSet) pst.executeQuery();


if(rs.next()){


txt_book.setText(rs.getString("book_id")) ;

txt_bookName.setText(rs.getString("book_name")) ;

txt_author.setText(rs.getString("author")) ;

txt_quantity.setText(rs.getString("quantity")) ;

}else{
    book_Error.setText("invalid book id");
}

}catch (Exception e) {

  e.printStackTrace();
//
}
 
    }
  
  
  public void updateBookCount(){
      int bookId = Integer.parseInt(txt_bookId.getText());
       try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","");
          
          String sql ="update bookdetails set quantity =quantity-1 where book_id =?";
          PreparedStatement pst = con.prepareStatement(sql);
          
     pst.setInt(1,bookId);


     int rowCount = pst.executeUpdate();

if(rowCount > 0){

JOptionPane.showMessageDialog(this,"book count updated");
int initialCount=Integer.parseInt(txt_quantity.getText());
txt_quantity.setText(Integer.toString(initialCount-1));
}else{
  JOptionPane.showMessageDialog(this,"can't update book count");
}     

      }catch(Exception e){
          e.printStackTrace();
      }
      
      
  }
    
  
  
  public void getStudentDetails(){
        
         int StudentId = Integer.parseInt(txt_studentId.getText());
         
try{

Class.forName("com.mysql.jdbc.Driver");

Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","");

 PreparedStatement pst = con.prepareStatement("select * from student_details where student_id = ?");
 pst.setInt(1,StudentId);
ResultSet rs =(ResultSet) pst.executeQuery();


if(rs.next()){


txt_id.setText(rs.getString("student_id")) ;

txt_studentName.setText(rs.getString("name")) ;

txt_course.setText(rs.getString("course")) ;

txt_branch.setText(rs.getString("branch")) ;

}else{
    student_Error.setText("invalid Student Id");
}

}catch (Exception e) {

  e.printStackTrace();
//
}
 
    }
  
  
  
  public boolean issueBook(){
      
      boolean isIssued=false;
      
      int bookId = Integer.parseInt(txt_bookId.getText());
      int StudentId = Integer.parseInt(txt_studentId.getText());
      String bookName = txt_bookName.getText();
      String studentName = txt_studentName.getText();
      
      Date uIssueDate = date_issueDate.getDatoFecha();
      Date uDueDate = date_dueDate.getDatoFecha();
      
      long l1 = uIssueDate.getTime();
      long l2 = uDueDate.getTime();
      
         uIssueDate = new java.sql.Date(l1);
         uDueDate = new java.sql.Date(l2);
         
      
      try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","");
          
          String sql ="insert into issue_book_details(book_id,book_name,student_id,student_name,"+"issue_date,due_date,status) value(?,?,?,?,?,?,?)";
          PreparedStatement pst = con.prepareStatement(sql);
          
          pst.setInt(1,bookId);
pst.setString(2,bookName);
pst.setInt(3,StudentId);
pst.setString(4,studentName);
pst.setDate(5, (java.sql.Date) uIssueDate);
pst.setDate(6, (java.sql.Date) uDueDate);
pst.setString(7,"pending");

     int rowCount = pst.executeUpdate();

if(rowCount > 0){
isIssued=true;

}else{
  isIssued=false;
}     

      }catch(Exception e){
          
      }
      return isIssued;
      
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCTextField4 = new app.bolivia.swing.JCTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_studentName = new javax.swing.JLabel();
        txt_course = new javax.swing.JLabel();
        txt_branch = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        studentError = new javax.swing.JLabel();
        student_Error = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jCTextField5 = new app.bolivia.swing.JCTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JLabel();
        txt_book = new javax.swing.JLabel();
        txt_bookName = new javax.swing.JLabel();
        txt_author = new javax.swing.JLabel();
        bookError = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        book_Error = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        date_dueDate = new rojeru_san.componentes.RSDateChooser();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        date_issueDate = new rojeru_san.componentes.RSDateChooser();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        txt_bookId = new app.bolivia.swing.JCTextField();
        txt_studentId = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Student Id :");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Create New Account Here");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Signup Page");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Username");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jCTextField4.setBackground(new java.awt.Color(0, 153, 153));
        jCTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField4.setPlaceholder("Enter Username");
        jCTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField4ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, 40));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Enter Student name :");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(" Course :");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Branch :");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STUDENT DETAILS");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        txt_studentName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_studentName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(txt_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 170, 50));

        txt_course.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_course.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(txt_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, 50));

        txt_branch.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_branch.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(txt_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 250, 50));

        txt_id.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 170, 50));

        studentError.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        studentError.setForeground(new java.awt.Color(204, 0, 51));
        jPanel7.add(studentError, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 190, -1));

        student_Error.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        student_Error.setForeground(new java.awt.Color(255, 255, 0));
        jPanel7.add(student_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 190, 50));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 370, 710));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Enter Book Id :");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Create New Account Here");
        jPanel10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel38.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Signup Page");
        jPanel10.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Username");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jCTextField5.setBackground(new java.awt.Color(0, 153, 153));
        jCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField5.setPlaceholder("Enter Username");
        jCTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField5ActionPerformed(evt);
            }
        });
        jPanel10.add(jCTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, 40));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Enter Book name :");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Author Name :");
        jPanel9.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 30));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel47.setText("Back");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BOOK DETAILS");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        txt_quantity.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_quantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 160, 30));

        txt_book.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_book.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(txt_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 156, 130, 30));

        txt_bookName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_bookName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(txt_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 246, 160, 30));

        txt_author.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt_author.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(txt_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 160, 30));

        bookError.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        bookError.setForeground(new java.awt.Color(204, 0, 51));
        jPanel9.add(bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Quantity :");
        jPanel9.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        book_Error.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        book_Error.setForeground(new java.awt.Color(255, 255, 0));
        jPanel9.add(book_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 190, 50));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 710));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setText("ISSUE BOOK");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, -1, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setText("Book Id :");
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, -1, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setText("Student Id :");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setText("Issue Date :");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel52.setText("Due Date :");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        date_dueDate.setBackground(new java.awt.Color(0, 0, 0));
        date_dueDate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        date_dueDate.setColorBackground(new java.awt.Color(0, 0, 0));
        date_dueDate.setColorForeground(new java.awt.Color(0, 0, 0));
        date_dueDate.setPlaceholder("");
        jPanel6.add(date_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, 2));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, -1, 2));

        date_issueDate.setBackground(new java.awt.Color(0, 0, 0));
        date_issueDate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        date_issueDate.setColorBackground(new java.awt.Color(0, 0, 0));
        date_issueDate.setColorForeground(new java.awt.Color(0, 0, 0));
        date_issueDate.setPlaceholder("");
        jPanel6.add(date_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, -1, -1));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(0, 153, 153));
        rSMaterialButtonCircle2.setText("ISSUE BOOK");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel6.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 200, 50));

        txt_bookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_bookId.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_bookId.setPlaceholder("Enter Book Id");
        txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookIdFocusLost(evt);
            }
        });
        txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIdActionPerformed(evt);
            }
        });
        jPanel6.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 190, -1));

        txt_studentId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_studentId.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_studentId.setPlaceholder("Enter Student Id");
        txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentIdFocusLost(evt);
            }
        });
        txt_studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentIdActionPerformed(evt);
            }
        });
        jPanel6.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 180, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:
           HomePage home = new HomePage();
       home.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jCTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField5ActionPerformed

    private void txt_studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentIdActionPerformed

    private void txt_studentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIdFocusLost
        // TODO add your handling code here:
         if(!txt_studentId.getText().equals("")){
            getStudentDetails();
        }
    }//GEN-LAST:event_txt_studentIdFocusLost

    private void jCTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField4ActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
         if(issueBook()==true){

JOptionPane.showMessageDialog(this,"book Issued successfully");
updateBookCount();

}else{

JOptionPane.showMessageDialog(this,"can't issue book");
}

    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void txt_bookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIdFocusLost
       
        if(!txt_bookId.getText().equals("")){
            getBookDetails();
        }
        
    }//GEN-LAST:event_txt_bookIdFocusLost

    private void txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookError;
    private javax.swing.JLabel book_Error;
    private rojeru_san.componentes.RSDateChooser date_dueDate;
    private rojeru_san.componentes.RSDateChooser date_issueDate;
    private app.bolivia.swing.JCTextField jCTextField4;
    private app.bolivia.swing.JCTextField jCTextField5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private javax.swing.JLabel studentError;
    private javax.swing.JLabel student_Error;
    private javax.swing.JLabel txt_author;
    private javax.swing.JLabel txt_book;
    private app.bolivia.swing.JCTextField txt_bookId;
    private javax.swing.JLabel txt_bookName;
    private javax.swing.JLabel txt_branch;
    private javax.swing.JLabel txt_course;
    private javax.swing.JLabel txt_id;
    private javax.swing.JLabel txt_quantity;
    private app.bolivia.swing.JCTextField txt_studentId;
    private javax.swing.JLabel txt_studentName;
    // End of variables declaration//GEN-END:variables
}
