/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

/**
 *
 * @author dell
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form issueBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jCTextField5 = new app.bolivia.swing.JCTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_password3 = new app.bolivia.swing.JCTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_email3 = new app.bolivia.swing.JCTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txt_contact3 = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_username6 = new app.bolivia.swing.JCTextField();
        txt_contact4 = new app.bolivia.swing.JCTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        txt_username4 = new app.bolivia.swing.JCTextField();
        txt_username3 = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle3 = new necesario.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Issue Id :");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 50, 50));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Create New Account Here");
        jPanel10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel38.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Signup Page");
        jPanel10.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Username");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jCTextField5.setBackground(new java.awt.Color(0, 153, 153));
        jCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCTextField5.setPlaceholder("Enter Username");
        jCTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField5ActionPerformed(evt);
            }
        });
        jPanel10.add(jCTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, 40));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 50, 50));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Book name");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        txt_password3.setBackground(new java.awt.Color(0, 153, 153));
        txt_password3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_password3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_password3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password3ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_password3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 60, 50));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Student Name");
        jPanel9.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 30));

        txt_email3.setBackground(new java.awt.Color(0, 153, 153));
        txt_email3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_email3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_email3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email3ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 180, 40));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel9.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 50, 60));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Issue Date");
        jPanel9.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        txt_contact3.setBackground(new java.awt.Color(0, 153, 153));
        txt_contact3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_contact3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_contact3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contact3ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_contact3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BOOK DETAILS");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        txt_username6.setBackground(new java.awt.Color(0, 153, 153));
        txt_username6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_username6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_username6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_username6FocusLost(evt);
            }
        });
        txt_username6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username6ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 180, -1));

        txt_contact4.setBackground(new java.awt.Color(0, 153, 153));
        txt_contact4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_contact4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_contact4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contact4ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_contact4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 180, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Due Date");
        jPanel9.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel9.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 50, 60));

        jLabel47.setBackground(new java.awt.Color(0, 153, 153));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel47.setText("Back");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 710));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setText("RETURN BOOK");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 160, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setText("Book Id :");
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setText("Student Id :");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, 2));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(0, 153, 153));
        rSMaterialButtonCircle2.setText("FIND BOOK");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel6.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 280, 50));

        txt_username4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_username4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_username4.setPlaceholder("Enter Book Id");
        txt_username4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_username4FocusLost(evt);
            }
        });
        txt_username4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username4ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 190, -1));

        txt_username3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_username3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_username3.setPlaceholder("Enter Student Id");
        txt_username3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_username3FocusLost(evt);
            }
        });
        txt_username3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username3ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 180, -1));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(0, 153, 153));
        rSMaterialButtonCircle3.setText("RETURN BOOK");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel6.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 270, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:
           HomePage home = new HomePage();
       home.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel47MouseClicked

    private void txt_contact3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contact3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contact3ActionPerformed

    private void txt_email3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email3ActionPerformed

    private void txt_password3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password3ActionPerformed

    private void jCTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField5ActionPerformed

    private void txt_username3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username3ActionPerformed

    private void txt_username3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username3FocusLost

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void txt_username4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username4FocusLost

    private void txt_username4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username4ActionPerformed

    private void txt_username6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username6FocusLost

    private void txt_username6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username6ActionPerformed

    private void txt_contact4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contact4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contact4ActionPerformed

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextField5;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private app.bolivia.swing.JCTextField txt_contact3;
    private app.bolivia.swing.JCTextField txt_contact4;
    private app.bolivia.swing.JCTextField txt_email3;
    private app.bolivia.swing.JCTextField txt_password3;
    private app.bolivia.swing.JCTextField txt_username3;
    private app.bolivia.swing.JCTextField txt_username4;
    private app.bolivia.swing.JCTextField txt_username6;
    // End of variables declaration//GEN-END:variables
}
